version: "3"
services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:latest
        environment:
            CPU_CORES: "1"
            DISK_SIZE: "16G"
            RAM_SIZE: "512M"
        devices:
            - /dev/kvm
            - /dev/vhost-net
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN        
        ports:
            - 5000:5000
        volumes:
            - /opt/dsm:/storage
        restart: on-failure
        stop_grace_period: 1m
