version: "3"
services:
    dsm:
        container_name: dsm
        image: vdsm/virtual-dsm:latest
        environment:
            DISK_SIZE: "16G"
            RAM_SIZE: "1G"
            CPU_CORES: "1"
        devices:
            - /dev/kvm
        device_cgroup_rules:
            - 'c *:* rwm'
        cap_add:
            - NET_ADMIN
        ports:
            - 5000:5000
        volumes:
            - /var/dsm:/storage
        restart: on-failure
        stop_grace_period: 2m
